### PR TITLE
Style suggestions

### PR DESCRIPTION
**Pull request by anouq**

### CODE REVIEW

**Review by alex-ns-nl — APPROVED** [review]
Good suggestions! is there an easier way to review the changes? It took me a while to figure out what the adjusted layout was compared to the original.. perhaps it would have been easier to have the two different files next to each other, for example


image

**Review by alex-ns-nl — COMMENTED** [review]
Ah yes, I knew this (not sure why I didn't stick to it)! thanks for pointing it out

**Review by alex-ns-nl — COMMENTED** [review]
I accidentally also merged this pull request (i think :P) What does the @ -1.3 +1.7 @@ do? I can't find this back in the w3schools document

**Comment by alex-ns-nl** [comment]
I won't delete the branch just yet (in case I lose the comments/questions that way ;))

**Comment by anouq** [comment]
> I won't delete the branch just yet (in case I lose the comments/questions that way ;))

sure, whatever you want. you can delete the branch though. the PR (which is where all these comments are) will remain available: https://github.com/Zandag3007/DivTest/pulls?q=is%3Apr+is%3Aclosed

**Comment by anouq** [comment]
> 



> I accidentally also merged this pull request (i think :P) What does the @ -1.3 +1.7 @@ do? I can't find this back in the w3schools document

those numbers indicate the line number (1) and character number (3, 7) where changes were made

**Comment by anouq** [comment]
> Good suggestions! is there an easier way to review the changes? It took me a while to figure out what the adjusted layout was compared to the original.. perhaps it would have been easier to have the two different files next to each other, for example
> 
> image

yep, thats possible. I use Intellij, and you can view changes side by side (I also like doing this). im sure you can do that too in your IDE (Atom, no?)

**Pull request merged**
